# Generated by Django 3.2 on 2021-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210510_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='distance',
        ),
        migrations.AddField(
            model_name='company',
            name='distance_bike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='distance_others',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='distance_plane',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='distance_ship',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='distance_train',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='distance_truck',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='short_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='transport_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='tonnage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
