# Generated by Django 3.2 on 2021-05-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_transport_per_day_company_transports_per_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvFile',
        ),
    ]
