# Generated by Django 3.2 on 2021-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210510_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='delivery',
            field=models.CharField(choices=[('internal', 'internal'), ('in', 'in'), ('out', 'out')], default='internal', max_length=10),
        ),
    ]
