# Generated by Django 3.2 on 2021-05-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_route_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='emissions',
            new_name='frequency',
        ),
    ]
