# Generated by Django 3.2 on 2021-05-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_emissions_route_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='distance_bike',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_others',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_plane',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_ship',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_train',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_truck',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration_bike',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration_max',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration_others',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration_plane',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration_ship',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration_train',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration_truck',
        ),
        migrations.RemoveField(
            model_name='route',
            name='energy_bike',
        ),
        migrations.RemoveField(
            model_name='route',
            name='energy_others',
        ),
        migrations.RemoveField(
            model_name='route',
            name='energy_plane',
        ),
        migrations.RemoveField(
            model_name='route',
            name='energy_ship',
        ),
        migrations.RemoveField(
            model_name='route',
            name='energy_train',
        ),
        migrations.RemoveField(
            model_name='route',
            name='energy_truck',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name_others',
        ),
        migrations.RemoveField(
            model_name='route',
            name='product',
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='transportation',
            field=models.CharField(choices=[('train', 'train'), ('truck', 'truck'), ('ship', 'ship'), ('plane', 'plane'), ('others', 'others')], default='others', max_length=10),
        ),
    ]
